---

name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get the tag version
        id: get_tag
        run: |
            echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Prepare Changelog
        run: |
          curl -L -o git-chglog https://github.com/PhilippHeuer/git-chglog/releases/download/v1.0.0/git-chglog_linux_amd64
          chmod +x git-chglog
          ./git-chglog -c .chglog/release.yml -o RELEASE.MD ${{steps.get_tag.outputs.tag}}

      - name: Update tags
        uses: haya14busa/action-update-semver@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag: ${{steps.get_tag.outputs.tag }}
          major_version_tag_only: false

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          draft: false
          prerelease: false
          tag_name: ${{steps.get_tag.outputs.tag}}
          name: ${{steps.get_tag.outputs.tag}}
          body_path: RELEASE.MD
